### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by djalmabright** [tenthirtyone/blocktools#9]
19:31 ~/blocktools $ python parser.py
Blocksize:       %u
Traceback (most recent call last):
  File "parser.py", line 5, in <module>
    print("Blocksize:\t %u") % uint4(blockfile,)
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
19:33 ~/blocktools $ python sight.py 1M.dat
Traceback (most recent call last):
  File "sight.py", line 5, in <module>
    from block import Block, BlockHeader
  File "/home/djalmabright/blocktools/block.py", line 6, in <module>
    class BlockHeader:
  File "/home/djalmabright/blocktools/block.py", line 9, in BlockHeader
    self.previousHash = hash32(blockchain)
NameError: name 'blockchain' is not defined

**Comment by tenthirtyone** [comment]
Not enough info here to do anything productive. Any help?
